### Numpy Where / Filtering

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
a<=6 #Condition checking

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [6]:
np.where(a<=6) #returning the True value of condition in row & column wise--1st is row and 2nd is column

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [7]:
a[np.where(a<=6)] #Values output for the condition

array([1, 2, 3, 4, 5, 6])

In [8]:
a[[0, 0, 0, 1, 1, 1],[0, 1, 2, 0, 1, 2]] #Values output for the condition

array([1, 2, 3, 4, 5, 6])

In [9]:
# Even Number checking inside a array matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[np.where(a%2==0)]

array([2, 4, 6, 8])

In [10]:
# Odd Number checking inside a array matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[np.where(a%2!=0)]

array([1, 3, 5, 7, 9])