In [1]:
# imporing numpy library
import numpy as np

In [9]:
a=a=[[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]]
arr=np.array(a)
print(arr)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [11]:
# matrix size
arr.shape #(r,c)---r=row,c=column

(3, 3)

In [12]:
# matrix row size
arr.shape[0]

3

In [13]:
# matrix column size
arr.shape[1]

3

In [21]:
#Matrix row size by len function
len(arr)

3

In [23]:
#Matrix datatype
arr.dtype

dtype('int32')

In [27]:
#Matrix datatype changing(int to float)
d=arr.astype("float")
print(arr) #old datatype
print(d) #new data type

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [29]:
#Matrix datatype changing(float to int)
e=d.astype("int")
print(d) #old datatype
print(e) #new data type

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [37]:
# Array, Row, Column in Matrix
d=[[1,2,3],[5,6,7]]
matrix_1=np.array(d) #matix (d) calling inside numpy as array format
row=matrix_1.shape[0] #row in matrix(matrix_1)
print(row)
column=matrix_1.shape[1] #column in matrix(matrix_1)
print(column)

2
3


In [40]:
# zero dimensional array
np.array(42).ndim

0

In [43]:
# zero dimensional array shape
np.array(42).shape

()

In [38]:
# 1 dimensional array
np.array([1,2,3,4]).ndim

1

In [42]:
# 1 dimensional array shape
np.array([1,2,3,4]).shape

(4,)

In [41]:
# 2 dimensional array
np.array([[1,2,3,4],[6,8,9,10]]).ndim

2

In [44]:
# 2 dimensional array shape
np.array([[1,2,3,4],[6,8,9,10]]).shape #row and column format---(r,c)---r=row,c=column

(2, 4)

In [45]:
# 3 dimensional array
np.array([[[1,2,3,4],[6,8,9,10]],[[1,2,3,4],[6,8,9,10]]]).ndim

3

In [46]:
# 3 dimensional array shape
np.array([[[1,2,3,4],[6,8,9,10]],[[1,2,3,4],[6,8,9,10]]]).shape #row ,column & depth format---(d,r,c)---d=depth,r=row,c=column

(2, 2, 4)

In [2]:
# shorting of matrix column wise
a=np.array([[2.1,1.2],[1.6,5.7]])
print(a)
a.sort(axis=0)
print(a)

[[2.1 1.2]
 [1.6 5.7]]
[[1.6 1.2]
 [2.1 5.7]]


In [52]:
# shorting of matrix row wise
a=np.array([[2.1,1.2],[1.6,5.7]])
print(a)
a.sort(axis=1)
print(a)

[[2.1 1.2]
 [1.6 5.7]]
[[1.2 2.1]
 [1.6 5.7]]


In [53]:
# Resize Array
a=np.array([[1,2,3,4],[6,8,9,10]])
a.resize(4,2) # (r,c)---r=row,c=column
print(a)

[[ 1  2]
 [ 3  4]
 [ 6  8]
 [ 9 10]]


In [56]:
# Append the array in flatten matrix (2 D Matrix)
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.append(a,b) #append operation of a nad b matrix and then flatten in a matrix(c)
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [59]:
# Flatten the array in 1d matrix
a=np.array([[1,2,3],[4,5,6]])
b=a.flatten()
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [62]:
# Insert elemnt in the array
a=np.array([[1,2,3],[4,5,6]])
b=np.insert(a,2,10) #(a,i,e)--->a=array variable,i=index of the array in flatten,e=element which is inserted  
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[ 1  2 10  3  4  5  6]


In [65]:
# Concatenation the array in horizontal axis
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b),axis=1)
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [66]:
# Concatenation the array in vertical axis
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b),axis=0)
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
# Transpose of a matrix
a=np.array([[1,2,3],[4,5,6]])
b=a.T
print(a) #old matrix(a)
print(b) #new transpose matrix

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [75]:
# Determinent of a matrix
a=np.array([[1,2],[4,5]])
b=np.linalg.det(a)
print(a) #old matrix(a)
print(b) #new determinent value of matrix (a)

[[1 2]
 [4 5]]
-2.9999999999999996


In [76]:
# Inverse of a matrix
a=np.array([[1,2],[4,5]])
b=np.linalg.inv(a)
print(a) #old matrix(a)
print(b) #Inverse of matrix (a)

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


## Generation

In [4]:
# Arrange
np.arange(1,10,dtype='float') #elements are float data type in a array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
# Arrange
np.arange(1,10,dtype='int') #elements are int data type in a array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Arrange
np.arange(1,10) #elements are int data type by default in a array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Arrange
np.arange(1,10,2)# 1 elements steping

array([1, 3, 5, 7, 9])

In [8]:
# Arrange
np.arange(1,10,3)# 2 elements steping

array([1, 4, 7])

In [9]:
# Arrange
np.arange(1,10,1)# 0 elements steping

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Linespace 
np.linspace(1,10,5) #a araay creating with 5 elemts from 1 to 10 with equal spacing

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
# Random Number 
np.random.random((3,3)) # a matrix creating with random number of 3*3(row=3,column=3)

array([[0.11904109, 0.35514064, 0.08371218],
       [0.23376314, 0.71918803, 0.15992706],
       [0.59125863, 0.91212148, 0.80417945]])

In [14]:
# Random Number 
np.random.random((5,3)) # a matrix creating with random number of 5*3(row=5,column=3)

array([[0.64905837, 0.31134002, 0.32696645],
       [0.18549926, 0.57563844, 0.72414251],
       [0.86270652, 0.03697103, 0.09441061],
       [0.33469609, 0.36627263, 0.86168543],
       [0.11083011, 0.55375926, 0.44512471]])

In [15]:
#zero matrix creation
np.zeros((5,2)) # all zeros are in float datatype

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#one matrix creation
np.ones((4,6)) # all ones are in float datatype

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
# Gaussian Distribution Generation
mu=0
sigma=1
np.random.normal(mu,sigma,size=1000)

array([-4.00088440e-01, -1.60933303e+00,  2.12167191e-01, -4.01599861e-01,
        7.73237887e-01, -2.72365288e-01,  1.15202900e-01,  1.04756865e+00,
        2.34817228e+00,  3.86033412e-01,  4.45104140e-02,  1.30071762e+00,
        8.47346090e-01, -4.44210045e-01, -1.40114655e+00, -2.65886531e-01,
        1.16108289e-01,  2.22789814e-01,  2.46854702e-01, -3.25979513e-01,
        1.39272651e+00,  1.29312794e+00,  2.06980088e-02, -5.14398668e-01,
       -1.96973171e+00, -1.08116004e+00, -1.08390019e+00,  7.52414049e-01,
       -4.41496982e-01, -1.54372904e+00,  1.16465068e+00,  1.86774444e+00,
       -2.33162549e+00,  3.71736266e-02,  3.95406687e-01,  1.13136955e+00,
       -4.51251264e-02, -1.78226299e-02, -3.38565793e-01,  1.28421325e+00,
        1.36909375e+00,  3.85954592e-01,  9.28703271e-01, -8.44091685e-01,
       -1.03382203e-02, -2.07595028e+00, -1.35877488e+00, -3.73181175e-01,
       -6.92460379e-01, -3.65504494e+00,  1.07819986e+00,  1.44251027e+00,
       -4.02086106e-01,  

In [19]:
# Log Normal Distribution
np.random.lognormal(12,5,size=500)

array([2.44616252e+01, 9.99837632e+03, 1.21820315e+04, 3.52215197e+02,
       2.21771247e+03, 3.70002007e+03, 3.78176972e+07, 1.92457912e+05,
       5.48373650e+05, 9.85820380e+01, 1.58858120e+06, 6.19028636e+05,
       1.38670831e+04, 1.76519807e+05, 3.91994232e+05, 3.17923166e+04,
       2.65755694e+03, 4.65032469e+07, 1.06409201e+04, 2.16397968e+04,
       6.82187155e+04, 2.38390381e+06, 1.11511003e+04, 7.09489396e+03,
       5.27898695e+01, 6.53938691e+02, 2.72268915e+01, 7.66615581e+06,
       1.45122580e+03, 2.11450569e+08, 5.01938684e+04, 1.48717655e+06,
       8.25205320e+07, 1.44834842e+06, 8.51424702e+09, 5.48147199e+05,
       1.31294602e+05, 1.29109452e-01, 5.27906767e+01, 1.79309063e+03,
       3.28906220e+04, 7.51660446e+04, 7.23149555e+00, 2.59875823e+05,
       1.26775000e+07, 5.28047159e+02, 3.71448830e+03, 9.68353844e+03,
       1.88584567e+03, 4.28358196e+03, 4.05531511e+06, 3.51689602e+05,
       6.13162537e+05, 1.33564431e+02, 1.72291491e+07, 1.85163080e+05,
      

In [21]:
# Log Normal Distribution
log_normal=np.random.lognormal(12,5,size=100)
print(log_normal)

[7.51047507e+00 6.24860187e+03 2.50665989e+00 2.76272407e+06
 2.66754568e+05 2.23481100e+02 1.53340585e+03 1.76779004e+05
 5.10068228e+05 7.30877337e+03 5.09266694e+04 6.36840391e+04
 1.97170267e+05 3.46356930e+08 2.62135530e+03 1.56393938e+07
 7.49926268e+02 1.30572487e+05 1.44901328e+01 1.01198760e+05
 1.52898921e+01 6.99775846e+02 6.34591585e+03 1.56320761e+07
 8.04135132e+08 1.86295717e+05 3.66576674e+03 5.16650378e+06
 5.36480462e+03 3.50655208e+01 4.98474869e+03 8.35280235e+03
 1.78796982e+05 7.92664653e+04 2.89616667e+01 2.23537484e+03
 3.91773313e+10 5.53935633e+04 1.05983784e+06 4.14548354e+05
 3.08191775e+10 2.55426641e+00 1.10204099e+04 6.38290208e+07
 2.86651300e+05 6.74878832e+08 8.60592621e+06 1.21367781e+03
 8.05458665e+04 9.08576947e+00 2.95106677e+02 2.39187054e+04
 9.93901760e+04 1.96330532e+05 2.29502785e+01 5.34922467e+04
 6.74114938e+07 8.88699552e+06 1.45945764e+04 7.16484667e+07
 8.74701489e+04 3.51394357e+03 4.28947085e+03 1.51382024e+03
 4.47154333e+02 1.011355

In [22]:
# Log Normal Distribution
log_normal=np.random.lognormal(12,5,size=100)
np.log(log_normal)

array([ 8.58121075, 12.46484537, 13.590094  , 11.64760048, 10.35973968,
       19.62844269, 14.49602501,  9.76777663, 15.83493592,  3.60065647,
        5.10056674,  4.68275301, 14.49507826, 12.00703102, 12.81257626,
        2.21291161,  9.2703067 , 20.952995  , 16.15138722, 16.92618587,
        8.65534295, 11.04946089, 10.82881394, 17.71914005, 14.11748826,
       15.75218787, 14.2415149 , 15.30236541, 11.18948212, 13.64775662,
        8.62268012, 12.28946661, 16.2884804 , 10.35217615, 10.72591671,
       14.5649324 , 11.68765872, 11.64403095,  3.91471134, 12.71321448,
       10.25146257, 16.25976091,  8.59352642, 18.15720783,  9.73049552,
       14.45557585, 10.1108327 , 20.10342996, 12.53989143, 16.29136729,
       16.47280782, 13.31553258, 20.47625419, 16.28328045,  7.23111384,
       17.09468753,  7.89198049, 21.00095674, 19.67636832,  9.73301384,
       19.73011906,  7.75650534, 11.61713147, 20.80837651,  9.32853566,
       12.438286  , 13.16501521,  1.46791928, 11.85113552, 10.28

In [27]:
# square root of elements inside a array
z=np.array([[1,2],[3,4]])
a=np.sqrt(z)
print(z)
print(a)

[[1 2]
 [3 4]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [28]:
# log base e (ln) of elements inside a array
z=np.array([[1,2],[3,4]])
a=np.log(z)
print(z)
print(a)

[[1 2]
 [3 4]]
[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [29]:
# log base 10 (log10()) of elements inside a array
z=np.array([[1,2],[3,4]])
a=np.log10(z)
print(z)
print(a)

[[1 2]
 [3 4]]
[[0.         0.30103   ]
 [0.47712125 0.60205999]]


In [36]:
# random choice
a=["a","b","c","e","f"]
np.random.choice(a,2,replace=True) # repetating value can be picking 

array(['c', 'c'], dtype='<U1')

In [45]:
# random choice
a=["a","b","c","e","f"]
np.random.choice(a,2,replace=False) # repetating value cannot be picking 

array(['f', 'c'], dtype='<U1')

In [60]:
# random choice
a=["a","b","c","e","f"]
np.random.choice(a,2,replace=False,p=[0.5,0.2,0.2,0.05,0.05]) # repetating value cannot be picking and each elements picking probability described

array(['a', 'c'], dtype='<U1')

In [64]:
# random choice
data=[]
a=["a","b","c","d","e"]
for i in range(1000):
    value=np.random.choice(a,1,replace=False,p=[0.5,0.2,0.2,0.05,0.05])[0] # repetating value cannot be picking 
    data.append(value)

print(data)

['e', 'a', 'a', 'a', 'a', 'b', 'c', 'a', 'a', 'a', 'a', 'a', 'b', 'd', 'b', 'a', 'd', 'b', 'a', 'a', 'a', 'a', 'a', 'c', 'a', 'b', 'a', 'a', 'd', 'd', 'a', 'a', 'c', 'a', 'a', 'd', 'a', 'a', 'a', 'e', 'a', 'a', 'a', 'a', 'e', 'b', 'a', 'a', 'c', 'b', 'b', 'e', 'a', 'b', 'c', 'a', 'a', 'd', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'e', 'd', 'a', 'a', 'a', 'c', 'a', 'c', 'c', 'a', 'b', 'c', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'd', 'b', 'a', 'a', 'a', 'c', 'c', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'c', 'e', 'c', 'a', 'b', 'a', 'b', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b', 'b', 'c', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'e', 'a', 'c', 'b', 'a', 'c', 'c', 'c', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'a', 'c', 'a', 'd', 'a', 'a', 'a', 'a', 'c', 'b', 'a', 'd', 'c', 'a', 'b', 'e', 'a', 'a', 'd', 'b', 'b', 'a', 'b', 'a', 'c', 'c', 'a', 'c', 'c', 'c', 'a', 'c', 'b', 'b', 'b', 'a', 'b', 'b', 'a', 'c', 'a', 'b', 'a', 'c', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'c', 'b', 'b', 'a',

In [66]:
z=data.count("a")
y=data.count("b")
x=data.count("c")
w=data.count("d")
v=data.count("e")
u=len(data)
print("Count of picking a is :",z)
print("Count of picking b is :",y)
print("Count of picking c is :",x)
print("Count of picking d is :",w)
print("Count of picking e is :",v)
print("Total Count of element is :",u)

Count of picking a is : 485
Count of picking b is : 199
Count of picking c is : 213
Count of picking d is : 54
Count of picking e is : 49
Total Count of element is : 1000
