In [1]:
a=[[1,2,3],[4,5,6],[7,8,9]]
for i in a:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [2]:
b=[[1,2,3],[4,5,6],[7,8,9]]
for i in b:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [5]:
#Element addition of matrix with help of list and for loop
result=[]
for i in range(3):
    temp=[0]*3
    for j in range(3):
        temp[j]=a[i][j]+b[i][j]
    result.append(temp)
print(result)

for k in result:
    print(k)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [6]:
#Element addition of matrix with help of list and for loop
result=[]
for i in range(3):
    temp=[]
    for j in range(3):
        temp.append(a[i][j]+b[i][j])
    result.append(temp)
print(result)

for k in result:
    print(k)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [7]:
#import Numpy
import numpy as np

In [8]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
b=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
matrix1=np.array(a) #array conversion of a matrix
matrix2=np.array(b) #array conversion of a matrix

print(matrix1) #printing the matrix
print(type(matrix1)) #datatype in array
print(matrix2) #printing the matrix
print(type(matrix2)) #datatype in array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [13]:
# Matrix addition operation
c=matrix1 + matrix2
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [14]:
# Matrix substraction operation
c=matrix1 - matrix2
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [15]:
# Matrix element multiplication operation
c=matrix1 * matrix2
print(c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [16]:
# Matrix dot multiplication operation
d=np.dot(matrix1,matrix2)
print(d)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [17]:
# Matrix dot multiplication operation
d=matrix1.dot(matrix2)
print(d)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [22]:
f=[[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]]

arr=np.array(f)
print(arr)
print(type(arr))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
<class 'numpy.ndarray'>


In [23]:
arr[:2,:2]

array([[30, 36],
       [66, 81]])

In [24]:
arr[1:,1:]

array([[ 81,  96],
       [126, 150]])

In [33]:
arr[[0,0,2,2],[0,2,0,2]]

array([ 30,  42, 102, 150])